stages:
  - tests

tests:
  stage: tests
  script:
    - pip3 install -r requirements.txt
    - pytest tests/unit --cov=app

complexity:
  stage: tests
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  stage: tests
  script:
    - flake8 *
